Repository iNESlab/Golbang_FE, pull requests merged in 2024-11, with the labels that each got.

#71 Feat: 프론트 수정
  golbang_jb/lib/main.dart
  golbang_jb/lib/models/club_member.dart
  golbang_jb/lib/models/group.dart
  golbang_jb/lib/pages/community/community_main.dart
  golbang_jb/lib/pages/event/event_detail.dart
  golbang_jb/lib/pages/group/group_main.dart
  golbang_jb/lib/pages/home/home_page.dart
  golbang_jb/lib/pages/logins/login.dart
  golbang_jb/lib/pages/logins/widgets/login_widgets.dart
  golbang_jb/lib/services/group_service.dart
  golbang_jb/lib/services/user_service.dart
  golbang_jb/lib/widgets/sections/bookmark_section.dart
  golbang_jb/lib/widgets/sections/groups_section.dart
  golbang_jb/lib/widgets/sections/upcoming_events.dart
  golbang_jb/pubspec.lock
  golbang_jb/pubspec.yaml
Labels: ✨feat

#72 Feat: 즐겨찾기 예외처리 추가
  golbang_jb/lib/pages/home/home_page.dart
  golbang_jb/lib/services/statistics_service.dart
Labels: ✨feat

#79 Feat & Fix: Flutter time zone 설정, 모임 생성 시 알림 메시지 추가, 기타 코드 리팩토링
  golbang_jb/lib/main.dart
  golbang_jb/lib/models/group.dart
  golbang_jb/lib/pages/event/event_create1.dart
  golbang_jb/lib/pages/event/event_main.dart
  golbang_jb/lib/pages/group/group_create.dart
  golbang_jb/lib/pages/group/group_main.dart
  golbang_jb/lib/pages/home/home_page.dart
  golbang_jb/lib/pages/logins/widgets/login_widgets.dart
  golbang_jb/lib/pages/profile/profile_screen.dart
  golbang_jb/lib/services/group_service.dart
  golbang_jb/lib/services/statistics_service.dart
  golbang_jb/lib/widgets/sections/upcoming_events.dart
Labels: ✨feat, 🔨fix

#80 Fix&Feat: Product Review에서 발생한 버그 해결, 수정해야 할 디자인 및 기능 추가
  golbang_jb/lib/models/group.dart
  golbang_jb/lib/pages/group/group_main.dart
  golbang_jb/lib/pages/profile/statistics_page.dart
  golbang_jb/lib/pages/profile/user_info_page.dart
  golbang_jb/lib/widgets/sections/group_item.dart
Labels: ✨feat, 🔨fix

#81 Fix&Feat: 알림 히스토리 페이지 수정 및 모임 설정 페이지 임시 제작
  golbang_jb/lib/pages/community/admin_settings_page.dart
  golbang_jb/lib/pages/community/community_main.dart
  golbang_jb/lib/pages/community/member_list_page.dart
  golbang_jb/lib/pages/community/member_manage_page.dart
  golbang_jb/lib/pages/community/member_settings_page.dart
  golbang_jb/lib/pages/group/group_main.dart
  golbang_jb/lib/pages/notification/notification_history_page.dart
  golbang_jb/lib/pages/signup/additional_info.dart
  golbang_jb/lib/services/club_service.dart
  golbang_jb/lib/services/event_service.dart
  golbang_jb/lib/services/notification_service.dart
  golbang_jb/lib/widgets/sections/groups_section.dart
  golbang_jb/pubspec.yaml
Labels: ✨feat

#74 Setting: 앱 버전 변경 및 릴리즈 환경 설정 & Fix: 웹소켓 페이지 버그 수정
  golbang_jb/android/app/build.gradle
  golbang_jb/lib/pages/game/overall_score_page.dart
  golbang_jb/lib/pages/game/score_card_page.dart
  golbang_jb/pubspec.lock
  golbang_jb/pubspec.yaml
Labels: 🔨fix
