Repository iNESlab/Golbang_FE, pull requests merged in 2024-12, with the labels that each got.

#82 Feat&Refactor: 페이지 이동 로직 추가 및 디자인/현재 시각 로직 리펙토링
  golbang_jb/lib/models/profile/club_profile.dart
  golbang_jb/lib/pages/event/event_detail.dart
  golbang_jb/lib/pages/event/event_main.dart
  golbang_jb/lib/pages/event/event_result.dart
  golbang_jb/lib/pages/event/widgets/team_result.dart
  golbang_jb/lib/pages/game/score_card_page.dart
Labels: bug, ✨feat, 🔨fix

#83 Feat&Fix: 코스 정보 디자인 코드 복구, 모임 생성-유저검색, 모임 메인-오버플로우해결&안내메세지 수정
  golbang_jb/lib/pages/event/event_detail.dart
  golbang_jb/lib/pages/group/group_create.dart
  golbang_jb/lib/pages/group/group_main.dart
  golbang_jb/lib/pages/logins/login.dart
  golbang_jb/lib/pages/signup/additional_info.dart
  golbang_jb/lib/widgets/sections/member_dialog.dart
Labels: ✨feat, 🔨fix

#85 Fix: 시간대 게임스코어 음수 입력 수정
  golbang_jb/android/build.gradle
  golbang_jb/lib/main.dart
  golbang_jb/lib/models/event.dart
  golbang_jb/lib/pages/event/event_create1.dart
  golbang_jb/lib/pages/event/event_create2.dart
  golbang_jb/lib/pages/event/event_detail.dart
  golbang_jb/lib/pages/event/event_main.dart
  golbang_jb/lib/pages/game/overall_score_page.dart
  golbang_jb/lib/pages/game/score_card_page.dart
  golbang_jb/lib/utils/AllowNavigateNumbersFormatter.dart
Labels: 🔨fix

#87 Deploy: 릴리즈 버전4 업데이트 및 버전 불일치 버그 수정
  golbang_jb/android/settings.gradle
  golbang_jb/pubspec.yaml
Labels: 🔨fix, 💀 deploy

#86 Fix&Feat: 엑셀파일 Transpose 및 팀별 정렬 & Event Detail 페이지에 Excel 파일 추출 버튼 추가
  golbang_jb/lib/pages/event/event_detail.dart
  golbang_jb/lib/pages/event/event_result_full_score_card.dart
  golbang_jb/pubspec.lock
Labels: ✨feat

#92 Hotfix: 자동 로그인 구현
  golbang_jb/lib/main.dart
  golbang_jb/lib/pages/home/splash_screen.dart
  golbang_jb/lib/pages/logins/login.dart
  golbang_jb/lib/repoisitory/secure_storage.dart
  golbang_jb/lib/services/auth_service.dart
Labels: ✨feat

#95 Hotfix: QA에서 발생한 회원가입&스코어카드 입력 쪽 문제 수정 및 App Link 포함 환경 설정
  golbang_jb/android/app/build.gradle
  golbang_jb/android/app/src/main/AndroidManifest.xml
  golbang_jb/android/build.gradle
  golbang_jb/android/gradle/wrapper/gradle-wrapper.properties
  golbang_jb/android/settings.gradle
  golbang_jb/lib/main.dart
  golbang_jb/lib/pages/event/widgets/ranking_list.dart
  golbang_jb/lib/pages/game/score_card_page.dart
  golbang_jb/lib/pages/logins/hi_screen.dart
  golbang_jb/lib/pages/notification/notification_history_page.dart
  golbang_jb/lib/pages/profile/statistics_page.dart
  golbang_jb/pubspec.lock
  golbang_jb/pubspec.yaml
Labels: ✨feat, 🔨fix

#97 Feat: 유저 서비스 기능 추가
  golbang_jb/lib/pages/logins/forget_password.dart
  golbang_jb/lib/pages/logins/login.dart
  golbang_jb/lib/pages/logins/widgets/forgot_password.dart
  golbang_jb/lib/pages/logins/widgets/login_widgets.dart
  golbang_jb/lib/pages/logins/widgets/social_login_widgets.dart
  golbang_jb/lib/pages/setting/setting_page.dart
  golbang_jb/lib/repoisitory/secure_storage.dart
  golbang_jb/lib/services/user_service.dart
  golbang_jb/pubspec.lock
Labels: ✨feat

#98 이벤트 링크 클릭시 이벤트 상세 페이지로 이동 구현.
  golbang_jb/android/app/src/main/AndroidManifest.xml
  golbang_jb/lib/main.dart
Labels: ✨feat

#99 Feat&Fix: 모임 버그 해결, 회원가입/로그인/설정 디자인 수정, 개인정보처리방침 등 이용약관 추가, 피드백 보내기 페이지 추가
  golbang_jb/lib/main.dart
  golbang_jb/lib/pages/common/privacy_policy_page.dart
  golbang_jb/lib/pages/community/admin_settings_page.dart
  golbang_jb/lib/pages/logins/hi_screen.dart
  golbang_jb/lib/pages/logins/login.dart
  golbang_jb/lib/pages/logins/widgets/login_widgets.dart
  golbang_jb/lib/pages/logins/widgets/social_login_widgets.dart
  golbang_jb/lib/pages/setting/feedback_page.dart
  golbang_jb/lib/pages/setting/setting_page.dart
  golbang_jb/lib/pages/signup/additional_info.dart
  golbang_jb/lib/pages/signup/marketing_agreement_page.dart
  golbang_jb/lib/pages/signup/signup.dart
  golbang_jb/lib/pages/signup/term_of_service_page.dart
  golbang_jb/lib/pages/signup/terms_agreement_page.dart
  golbang_jb/lib/pages/signup/widgets/signup_widgets.dart
  golbang_jb/lib/pages/signup/widgets/welcome_header_widget.dart
  golbang_jb/lib/services/club_member_service.dart
  golbang_jb/lib/services/feedback_service.dart
  golbang_jb/lib/services/group_service.dart
  golbang_jb/pubspec.lock
  golbang_jb/pubspec.yaml
Labels: ✨feat, 🔨fix

#100 Docs: 개인정보 처리방침 내용 수정
  golbang_jb/lib/pages/common/privacy_policy_page.dart
  golbang_jb/pubspec.lock
  golbang_jb/pubspec.yaml
Labels: 🔨fix

#101 Fix: 이벤트 생성시 유저가 관리자인 모임만 보이도록 필터링
  golbang_jb/.gitignore
  golbang_jb/lib/pages/event/event_create1.dart
  golbang_jb/lib/services/club_service.dart
Labels: 🔨fix

#103 Hotfix: 버그 수정, 비공개 테스트 전 UI 및 스타일 관련하여 보완
  golbang_jb/lib/models/event.dart
  golbang_jb/lib/pages/event/event_detail.dart
  golbang_jb/lib/pages/event/event_update2.dart
  golbang_jb/lib/pages/event/widgets/event_header.dart
  golbang_jb/lib/pages/event/widgets/mini_score_card.dart
  golbang_jb/lib/pages/game/score_card_page.dart
  golbang_jb/lib/pages/profile/statistics_page.dart
  golbang_jb/lib/pages/profile/user_info_page.dart
  golbang_jb/lib/widgets/sections/groups_section.dart
  golbang_jb/pubspec.lock
Labels: 🔨fix

#104 Fix&Design: 홈 메인 버그 픽스 및 게임 결과 전체 스코어 디자인변경
  golbang_jb/lib/pages/event/event_result_full_score_card.dart
  golbang_jb/lib/pages/event/widgets/SummaryDataTable.dart
  golbang_jb/lib/pages/home/home_page.dart
  golbang_jb/lib/widgets/sections/groups_section.dart
  golbang_jb/lib/widgets/sections/upcoming_events.dart
Labels: 🔨fix

#105 Hotfix: group_section 충돌난 부분 추가 제거
  golbang_jb/lib/pages/logins/login.dart
  golbang_jb/lib/widgets/sections/groups_section.dart
  golbang_jb/pubspec.yaml
Labels: 🔨fix
