Repository iNESlab/Golbang_FE, pull requests merged in 2025-01, with the labels that each got.

#107 hotJungBeom: iOS 설정 파일 수정 (flutter.h 등 에러 디버깅) (중범선배 기여작품)
  golbang_jb/ios/Flutter/Debug.xcconfig
  golbang_jb/ios/Flutter/Release.xcconfig
  golbang_jb/ios/Podfile
  golbang_jb/ios/Podfile.lock
  golbang_jb/ios/Runner.xcodeproj/project.pbxproj
  golbang_jb/lib/main.dart
  golbang_jb/pubspec.lock
  golbang_jb/pubspec.yaml
Labels: bug

#108 hotfix: iOS FCM 토큰 초기 설정
  golbang_jb/ios/Podfile
  golbang_jb/ios/Runner.xcodeproj/project.pbxproj
  golbang_jb/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  golbang_jb/ios/Runner/GoogleService-Info.plist
  golbang_jb/ios/Runner/Info.plist
  golbang_jb/lib/main.dart
Labels: bug, 🔨fix

#110 hotJB: iOS - googleMap SDK 관련 에러를 해결하기 위해 구글맵API 설정값 추가
  golbang_jb/ios/Podfile.lock
  golbang_jb/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  golbang_jb/ios/Runner/AppDelegate.swift
Labels: 🔨fix

#112 Feat: 이벤트메인/대시보드 UI 개선, 스코어카드 디자인 업데이트
  golbang_jb/.gitignore
  golbang_jb/ios/Podfile.lock
  golbang_jb/ios/Runner.xcodeproj/project.pbxproj
  golbang_jb/lib/pages/event/event_main.dart
  golbang_jb/lib/pages/event/widgets/mini_score_card.dart
  golbang_jb/lib/pages/logins/login.dart
  golbang_jb/lib/services/user_service.dart
  golbang_jb/lib/widgets/sections/bookmark_section.dart
  golbang_jb/lib/widgets/sections/upcoming_events.dart
  golbang_jb/pubspec.lock
Labels: ✨feat

#113 Fix&Refactor: AutoLogin & Game & Screen Size Riverpod
  golbang_jb/android/app/google-services.json
  golbang_jb/lib/global/LoginInterceptor.dart
  golbang_jb/lib/main.dart
  golbang_jb/lib/models/profile/club_profile.dart
  golbang_jb/lib/models/socket/rank.dart
  golbang_jb/lib/pages/event/event_detail.dart
  golbang_jb/lib/pages/game/overall_score_page.dart
  golbang_jb/lib/pages/game/score_card_page.dart
  golbang_jb/lib/pages/logins/login.dart
  golbang_jb/lib/pages/providers/user_provider.dart
  golbang_jb/lib/provider/screen_riverpod.dart
Labels: bug, 🔨fix

#114 refactor: env가 아닌 기존의 localProperties에서 API키 읽어오도록 변경
  golbang_jb/android/app/build.gradle
Labels: 🔨fix

#115 Feat&Fix: 프로필 기본 아이콘 적용, 이벤트 시간 UI 개선 및 버그 수정
  golbang_jb/assets/images/followme.png
  golbang_jb/assets/images/user_default.png
  golbang_jb/ios/.gitignore
  golbang_jb/lib/models/create_participant.dart
  golbang_jb/lib/models/event.dart
  golbang_jb/lib/models/member.dart
  golbang_jb/lib/models/profile/get_event_result_participants_ranks.dart
  golbang_jb/lib/models/profile/member_profile.dart
  golbang_jb/lib/models/socket/rank.dart
  golbang_jb/lib/models/update_event_participant.dart
  golbang_jb/lib/pages/community/member_list_page.dart
  golbang_jb/lib/pages/community/member_manage_page.dart
  golbang_jb/lib/pages/event/event_create1.dart
  golbang_jb/lib/pages/event/event_create2.dart
  golbang_jb/lib/pages/event/event_detail.dart
  golbang_jb/lib/pages/event/event_update1.dart
  golbang_jb/lib/pages/event/event_update2.dart
  golbang_jb/lib/pages/event/widgets/no_api_participant_dialog.dart
  golbang_jb/lib/pages/event/widgets/participant_dialog.dart
  golbang_jb/lib/pages/event/widgets/ranking_list.dart
  golbang_jb/lib/pages/event/widgets/user_profile.dart
  golbang_jb/lib/pages/game/overall_score_page.dart
  golbang_jb/lib/services/auth_service.dart
  golbang_jb/lib/widgets/common/circular_default_person_icon.dart
  golbang_jb/lib/widgets/sections/upcoming_events.dart
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/app_links_linux
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/file_selector_linux
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/flutter_local_notifications_linux
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/flutter_secure_storage_linux
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/gtk
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/image_picker_linux
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/path_provider_linux
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/share_plus
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/shared_preferences_linux
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux
  golbang_jb/linux/flutter/generated_plugin_registrant.cc
  golbang_jb/linux/flutter/generated_plugin_registrant.h
  golbang_jb/linux/flutter/generated_plugins.cmake
  golbang_jb/macos/Flutter/GeneratedPluginRegistrant.swift
  golbang_jb/macos/Flutter/ephemeral/Flutter-Generated.xcconfig
  golbang_jb/macos/Flutter/ephemeral/flutter_export_environment.sh
  golbang_jb/pubspec.yaml
Labels: ✨feat, 🔨fix

#116 Fix: 스코어 카드 에러 최종 수정
  golbang_jb/lib/pages/event/event_detail.dart
  golbang_jb/lib/pages/event/event_main.dart
  golbang_jb/lib/pages/game/score_card_page.dart
Labels: bug, 🔨fix

#117 fix: height 초기화 전에 렌더링되는 버그 수정
  golbang_jb/lib/pages/game/score_card_page.dart
  golbang_jb/lib/services/auth_service.dart
Labels: 🔨fix
