Repository iNESlab/Golbang_FE, pull requests merged in 2025-02, with the labels that each got.

#119 [hotfix] 모임 메인 페이지 Overflow 해결, 회원가입 시 전화번호, 생년월일을 Optional로 변경, Cale…
  golbang_jb/lib/models/user_account.dart
  golbang_jb/lib/pages/event/event_main.dart
  golbang_jb/lib/pages/signup/additional_info.dart
  golbang_jb/lib/services/user_service.dart
  golbang_jb/lib/widgets/sections/group_item.dart
Labels: ✨feat, 🔨fix

#120 [iOS 빌드 최적화 및 개인정보처리방침 수정] iOS 심사 대응 및 빌드 프로세스 개선
  golbang_jb/ios/Runner/Info.plist
  golbang_jb/lib/pages/common/privacy_policy_page.dart
  golbang_jb/pubspec.yaml
Labels: 🔨fix, 💀 deploy

#122 [Fix] 통계 페이지 버튼 간격, 홈 화면 다가오는 이벤트 정렬 방식 & 구글맵 장소 변경시 반영 안되었던 이슈 해결
  golbang_jb/lib/pages/event/event_create1.dart
  golbang_jb/lib/pages/home/home_page.dart
  golbang_jb/lib/pages/profile/statistics_page.dart
Labels: 🔨fix

#121 JB: iOS 심사 거절사유인 구글 맵 튕기는 문제 수정
  .gitignore
  golbang_jb/ios/.gitignore
  golbang_jb/ios/Podfile
  golbang_jb/ios/Runner/AppDelegate.swift
  golbang_jb/ios/Runner/Info.plist
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/project/PROJECT@v11_mod=faba4e38afff62c0f77f2a1c98923e74_hash=bfdfe7dc352907fc980b868725387e98plugins=1OJSG6M1FOV3XYQCBH7Z29RZ0FPR9XDE1-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=086beb6ef7a3f7776557522b20da7fbf-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=0afdae842714042fe93c77d3bdc3a4ce-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=0f68747471cde219e6b6e132ccb9f5e0-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=1db60754e4a45063bcad603b686338dd-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=340100f037c7ef70497241bb8f5980ff-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=394507c86a9fd729467622e492c859d0-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=3bd5933f0131f8ec8db2c6ca9c1a0f52-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=3ed052ac97b928086b320001440360f0-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=43bb5c7090831d2808c2b01379362586-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=577e4668142ad19ff8cfef5653878ee2-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=5bf7ae0292f843d3a0e5d2c696165770-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=6a0d7bd4131779f94f3253581df830a3-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=72ff8b4baf4687fd061a4f4b90b79613-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=73138ec5e40a27ff6934ae45d698d85d-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=800ac8a00a45dc1056e7f4d71f5239e4-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=88e55ea1ca8619f39677a184d561ba5e-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=8d689c792272e97af7ddad2e661aa5a4-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=9dc4b3ca1be9cb241ef2a3e01b3bbb9f-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=a10c75d316595dad51b93dcb71d88b3c-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=a31cc69b9e21e0815a8ce14c94231dc1-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=ade32a44f81f6c825bdf7fbf440e411f-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=ae5cc5a61f13050ea2e018cf522a8e92-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=b6a6ab3b670d245febd7aa1f846cf4ae-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=b992124a0af7d2dc7fa35c3614d2cf64-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=c2c9d8541c89901b743caa7e6c05302a-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=c374c9f188fc71d898001805cf8989a8-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=c6f540368184b272de5c4ab29ed3ef00-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=d5a8cb2d398b146195efb64774180b62-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=daa2e920aed538eb910a585b80828c38-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=e2ce641e8369b472daad48d4995ce4a9-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=ee2b48c78fd3e84b0c2039d1104a3368-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=f27e752ffe1bda435e9da12e2ff9ed88-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=f5874f07cc79dbad6aa1c2c84b015139-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/target/TARGET@v11_hash=ffbec5c4160677bfc1a8fcbb12e14f03-json
  golbang_jb/ios/build/ios/XCBuildData/PIFCache/workspace/WORKSPACE@v11_hash=(null)_subobjects=d100ca7b31cc727c1da4f2e88464cdf6-json
  golbang_jb/lib/main.dart
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/app_links_linux
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/file_selector_linux
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/flutter_local_notifications_linux
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/flutter_secure_storage_linux
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/gtk
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/image_picker_linux
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/path_provider_linux
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/share_plus
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/shared_preferences_linux
  golbang_jb/linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux
  golbang_jb/linux/flutter/generated_plugin_registrant.cc
  golbang_jb/linux/flutter/generated_plugin_registrant.h
  golbang_jb/linux/flutter/generated_plugins.cmake
  golbang_jb/macos/Flutter/GeneratedPluginRegistrant.swift
  golbang_jb/macos/Flutter/ephemeral/Flutter-Generated.xcconfig
  golbang_jb/macos/Flutter/ephemeral/flutter_export_environment.sh
  golbang_jb/pubspec.yaml
Labels: bug, 🔨fix

#124 feat: 클럽 회원 초대 API 연동
  golbang_jb/lib/pages/community/member_list_page.dart
  golbang_jb/lib/pages/community/member_manage_page.dart
  golbang_jb/lib/pages/community/member_settings_page.dart
  golbang_jb/lib/pages/group/group_create.dart
  golbang_jb/lib/services/club_service.dart
  golbang_jb/lib/services/group_service.dart
  golbang_jb/lib/widgets/sections/member_dialog.dart
Labels: ✨feat, 🔨fix
