Repository iNESlab/Golbang_FE, pull requests merged in 2025-03, with the labels that each got.

#125 [Feat] 멤버추가 기능 및 레이아웃 업데이트
  golbang_jb/lib/models/group.dart
  golbang_jb/lib/pages/community/admin_settings_page.dart
  golbang_jb/lib/pages/community/member_list_page.dart
  golbang_jb/lib/pages/community/member_settings_page.dart
  golbang_jb/lib/services/club_service.dart
Labels: ✨feat

#126 [Feat] 멤버추가 기능 및 레이아웃 업데이트 2
  golbang_jb/lib/widgets/sections/community_member_dialog.dart
Labels: ✨feat

#127 Refactor&Feat: 회원가입시 캘린더로 생년월일 입력, 멤버 추방(터치 시각효과 및 설명문 추가), 골프장 리스트 조회 API연동
  golbang_jb/lib/models/responseDTO/CourseResopnseDTO.dart
  golbang_jb/lib/models/responseDTO/LocationResponseDTO.dart
  golbang_jb/lib/pages/community/member_list_page.dart
  golbang_jb/lib/pages/event/event_create1.dart
  golbang_jb/lib/pages/event/event_update1.dart
  golbang_jb/lib/pages/event/widgets/location_search_dialog.dart
  golbang_jb/lib/pages/signup/additional_info.dart
  golbang_jb/lib/pages/signup/signup.dart
  golbang_jb/lib/pages/signup/widgets/calendar.dart
  golbang_jb/lib/repoisitory/secure_storage.dart
  golbang_jb/lib/services/event_service.dart
Labels: ✨feat, 🔨fix

#128 Fix: 골프장 조회 API 및 이벤트 조회 API
  golbang_jb/lib/models/event.dart
  golbang_jb/lib/models/golf_club_data.dart
  golbang_jb/lib/models/responseDTO/CourseResopnseDTO.dart
  golbang_jb/lib/models/responseDTO/GolfClubResponseDTO.dart
  golbang_jb/lib/models/responseDTO/LocationResponseDTO.dart
  golbang_jb/lib/pages/event/event_create1.dart
  golbang_jb/lib/pages/event/event_detail.dart
  golbang_jb/lib/pages/event/event_update1.dart
  golbang_jb/lib/pages/event/widgets/location_search_dialog.dart
  golbang_jb/lib/services/event_service.dart
Labels: 🔨fix

#129 Fix: CourseResposneDTO: pars null safe처리
  golbang_jb/lib/models/responseDTO/CourseResopnseDTO.dart
Labels: 🔨fix

#131 Fix: Timezone 수정
  golbang_jb/lib/models/create_event.dart
  golbang_jb/lib/models/event.dart
  golbang_jb/lib/models/post.dart
  golbang_jb/lib/models/user.dart
Labels: 🔨fix

#132 Feat: 통계 연도별 조회할 수 있는 드롭다운 기능 추가, UI 개선
  golbang_jb/lib/pages/profile/statistics_page.dart
Labels: ✨feat

#133 Feat: Event Create - 관리자 안내 문구 추가, Game-Ranking - 점수 표기 안내 다이얼로그, Event & EventDetail 게임 진행 상태 관리
  golbang_jb/lib/pages/event/event_create1.dart
  golbang_jb/lib/pages/event/event_detail.dart
  golbang_jb/lib/pages/event/event_main.dart
  golbang_jb/lib/pages/game/overall_score_page.dart
  golbang_jb/lib/provider/event/game_in_progress_provider.dart
Labels: ✨feat, 🔨fix

#134 Fix&Bug: 이벤트 수정 기능
  golbang_jb/lib/pages/event/event_create2.dart
  golbang_jb/lib/pages/event/event_update2.dart
Labels: bug, 🔨fix

#135 design(signup): 회원가입을 위한 약관동의 화면, 회원가입 1단계 화면 반응형으로 디자인 보완
  golbang_jb/lib/pages/signup/signup.dart
  golbang_jb/lib/pages/signup/terms_agreement_page.dart
  golbang_jb/lib/pages/signup/widgets/welcome_header_widget.dart
Labels: ✨feat, 🔨fix

#136 Refactor&Feat: 전반적으로 변수명을 가독성 높이기위해 수정했고, 모임 수정 및 버전 자동화 기능 추가했습니다.
  golbang_jb/lib/main.dart
  golbang_jb/lib/models/event.dart
  golbang_jb/lib/models/group.dart
  golbang_jb/lib/models/member.dart
  golbang_jb/lib/models/profile/get_all_user_profile.dart
  golbang_jb/lib/models/update_event_participant.dart
  golbang_jb/lib/pages/club/club_create_page.dart
  golbang_jb/lib/pages/club/club_edit_page.dart
  golbang_jb/lib/pages/club/club_main.dart
  golbang_jb/lib/pages/club/widgets/admin_button_widget.dart
  golbang_jb/lib/pages/club/widgets/member_button_widget.dart
  golbang_jb/lib/pages/community/admin_settings_page.dart
  golbang_jb/lib/pages/community/community_main.dart
  golbang_jb/lib/pages/community/member_list_page.dart
  golbang_jb/lib/pages/event/event_detail.dart
  golbang_jb/lib/pages/event/widgets/participant_dialog.dart
  golbang_jb/lib/pages/event/widgets/user_profile.dart
  golbang_jb/lib/pages/game/overall_score_page.dart
  golbang_jb/lib/pages/game/score_card_page.dart
  golbang_jb/lib/pages/home/home_page.dart
  golbang_jb/lib/pages/profile/statistics_page.dart
  golbang_jb/lib/pages/setting/setting_page.dart
  golbang_jb/lib/pages/signup/additional_info.dart
  golbang_jb/lib/services/club_service.dart
  golbang_jb/lib/utils/AllowNavigateNumbersFormatter.dart
  golbang_jb/lib/widgets/common/circular_default_person_icon.dart
  golbang_jb/lib/widgets/sections/admin_invite.dart
  golbang_jb/lib/widgets/sections/group_item.dart
  golbang_jb/lib/widgets/sections/groups_section.dart
  golbang_jb/lib/widgets/sections/member_dialog.dart
  golbang_jb/lib/widgets/sections/user_dialog.dart
  golbang_jb/pubspec.yaml
Labels: ✨feat

#137 Feat&Bug: 관리자 기능은 API URL에 admin이 들어가도록 추가(모임 삭제, 멤버 초대, 멤버 강퇴)]
  golbang_jb/lib/services/club_service.dart
  golbang_jb/pubspec.lock
Labels: bug, ✨feat

#138 Feat&BugFix: 모임 상태 업데이트 및 UI/UX 개선 - 모임 생성/삭제, 이벤트 안내 메시지 수정
  golbang_jb/lib/pages/club/club_create_page.dart
  golbang_jb/lib/pages/club/club_edit_page.dart
  golbang_jb/lib/pages/club/club_main.dart
  golbang_jb/lib/pages/community/admin_settings_page.dart
  golbang_jb/lib/pages/event/event_main.dart
Labels: ✨feat

#140 Fix: 코드 병합 후 에러 수정 및 이외 버그 수정
  golbang_jb/ios/Runner.xcodeproj/project.pbxproj
  golbang_jb/lib/pages/club/club_create_page.dart
  golbang_jb/lib/pages/club/club_edit_page.dart
  golbang_jb/lib/pages/community/admin_settings_page.dart
  golbang_jb/lib/pages/community/member_list_page.dart
  golbang_jb/lib/pages/event/event_main.dart
  golbang_jb/lib/provider/club/club_state_provider.dart
Labels: 🔨fix

#141 Fix: 클럽 메인화면에서 community이동시, 멤버 수정내역이 반영이 안되던 문제
  golbang_jb/lib/pages/club/club_main.dart
  golbang_jb/lib/pages/community/community_main.dart
  golbang_jb/lib/provider/club/club_state_provider.dart
  golbang_jb/lib/widgets/sections/groups_section.dart
Labels: 🔨fix

#142 hotix: 모임 및 관리자 변경 페이지 구독 에러
  golbang_jb/lib/pages/club/club_edit_page.dart
Labels: 🔨fix

#145 Fix: 모임 수정 페이지 provider null에러 임시 조치
  golbang_jb/lib/pages/club/club_edit_page.dart
  golbang_jb/lib/pages/community/admin_settings_page.dart
Labels: 🔨fix
